
name: lint-test-deploy

run-name: lint-test-deploy

on:
  push:
    branches:
      - main
      - dev

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Deploy
        run: echo "deploying ..."

      - name: Done
        run: echo "done"


  test:

    needs: lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          node-cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{env.node-cache-name}}-${{ hashFile('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm run test


  build:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          node-cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{node-cache-name}}-${{ hashFile('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci


  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: npm ci

      - name: Deploy
        run: echo "deploying ..."

      - name: Done
        run: echo "done"
